// <auto-generated />
using FleetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FleetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260224103014_InitialBaseline")]
    partial class InitialBaseline
    {
        protected void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}